In [1]:
import pandas as pd
import numpy as np
from sklearn.metrics import confusion_matrix

### Read the set of labels into a dataframe

In [2]:
labels = pd.read_csv('labels.csv')

In [3]:
labels.head()

perfect_labeler radiologist  algorithm
0          cancer      cancer       0.99
1          cancer      cancer       0.94
2          cancer      cancer       0.73
3          cancer      cancer       0.82
4          cancer      cancer       0.98

## Start with assesing the radiologist's performance
  * Assess the *acuracy* of the radiologist by looking at the  of     the cases that they correctly labeled.  
  *  Next, look at the true positive and true negative rates of the radiologist by generating a confusion matrix

In [4]:
                          
radiologist_accuracy = sum(labels.perfect_labeler == labels.radiologist)/len(labels)


In [5]:
radiologist_accuracy

0.8993288590604027

In [6]:
confusion_matrix(labels.perfect_labeler.values, labels.radiologist.values, labels=["cancer","benign"])

array([[ 25,   4],
       [ 11, 109]])

# Now look at the algorithm's performance compared to the perfect labeler:
   * Since the algorithm doesn't create a binary label, it instead returns a probability of cancer, choose a probability cut-off to use for the algorithm's labelling of cancer vs benign. (Hint: 0.5 is a reasonable starting place)
   * start assessing accuracy again here
   * Generate a confusion matrix

In [7]:
## Here, I'm going to change my entirre dataframe to 0's and 1's to make processing easier
labels = labels.replace('cancer',1).replace('benign',0)

In [8]:
labels.head()

perfect_labeler  radiologist  algorithm
0                1            1       0.99
1                1            1       0.94
2                1            1       0.73
3                1            1       0.82
4                1            1       0.98

In [9]:
algorithm_thresh = (labels.algorithm > 0.5)

In [10]:
confusion_matrix(labels.perfect_labeler.values, algorithm_thresh,labels=[1,0])

array([[ 21,   8],
       [  8, 112]])

What happens now if you change the threshold cut-off for your algorithm's classification to 0.4? What if you raise it to 0.6? How do accuracy, fp, fn, tp, and tn change?

In [11]:
algorithm_thresh = (labels.algorithm > 0.4)

In [12]:
confusion_matrix(labels.perfect_labeler.values,algorithm_thresh,labels=[1,0])

array([[ 25,   4],
       [ 16, 104]])

In [14]:
algorithm_thresh = (labels.algorithm > 0.6)

In [15]:
confusion_matrix(labels.perfect_labeler.values,algorithm_thresh,labels=[1,0])

array([[ 20,   9],
       [  5, 115]])

### Finally, let's compare our algorithm to the radiologist
* A "perfect labeler" might not exist in the real world, and in fact, if often does not
* In AI for medical imaging, using a radiologist's labels as our "true" label is often the standard of practice, and algorithm performance is judged in both an academic setting as well as in the regulated industry landscape based on performance against an expert human

* Repeat the steps above using a set threshold for your algorithm (again, 0.5 is perfectly reasonable) but now computing accuracy, tp, tn, fp, fn against the radiologist.