In [1]:
import numpy as np

In [2]:
arr1 = np.array([1,2,3], dtype=np.float64)

In [3]:
arr2 = np.array([1,2,3], dtype=np.float32)

In [4]:
arr1


array([1., 2., 3.])

In [5]:
arr2

array([1., 2., 3.], dtype=float32)

In [6]:
arr3 = np.array([1,2,3], dtype=np.int8)

In [7]:
arr3


array([1, 2, 3], dtype=int8)

In [8]:
arr = np.array([3.7, -1.2, -2.6, 0.5, 12.9, 10.1])


In [9]:
arr


array([ 3.7, -1.2, -2.6,  0.5, 12.9, 10.1])

In [10]:
arr.astype(np.int32)

array([ 3, -1, -2,  0, 12, 10], dtype=int32)

In [11]:
 numeric_strings = np.array(['1.25', '-9.6', '42'], dtype=np.string_)


In [12]:
numeric_strings


array([b'1.25', b'-9.6', b'42'], dtype='|S4')

In [13]:
numeric_strings.astype(float)

array([ 1.25, -9.6 , 42.  ])

In [14]:
int_array = np.arange(10)

In [15]:
calibers = np.array([.22, .270, .357, .380, .44, .50], dtype=np.float64)

In [16]:
int_array.astype(calibers.dtype)

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [17]:
empty_uint32 = np.empty(8, dtype='u4')

empty_uint32

In [18]:
empty_uint32 = np.empty(8, dtype='u4')

In [19]:
empty_uint32

array([   0,    0, 2043,    0,    8,    0,    8,    0], dtype=uint32)

In [20]:
arr = np.arange(10)


In [21]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [22]:
arr[5]

5

In [23]:
arr[1]

1

In [24]:
arr[0]

0

In [25]:
arr[5:8]

array([5, 6, 7])

In [26]:
arr[5:8] = 100

In [27]:
arr

array([  0,   1,   2,   3,   4, 100, 100, 100,   8,   9])

In [28]:
arr_slice = arr[5:8]

In [29]:
arr_slice

array([100, 100, 100])

In [30]:
arr_slice[1] = 12345

In [31]:
arr

array([    0,     1,     2,     3,     4,   100, 12345,   100,     8,
           9])

In [34]:
arr_slice[:] = 64

In [36]:
arr[5:8].copy()

array([64, 64, 64])

In [37]:
 arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])



In [39]:
arr2d[2]

array([7, 8, 9])

In [42]:
arr2d[2][0]*5

35