In [1]:
import pandas as pd


In [2]:
from pandas import Series, DataFrame

In [12]:
obj = pd.Series([4, 7, -5, 3], dtype='int32')

In [13]:
obj

0    4
1    7
2   -5
3    3
dtype: int32

In [14]:
obj.array

<PandasArray>
[4, 7, -5, 3]
Length: 4, dtype: int32

In [15]:
obj.shape

(4,)

In [16]:
obj.size

4

In [18]:
obj.index


RangeIndex(start=0, stop=4, step=1)

In [20]:
obj2 = pd.Series([4, 7, -5, 3], index=['d','a','b','c'])

In [21]:
obj

0    4
1    7
2   -5
3    3
dtype: int32

In [22]:
obj2

d    4
a    7
b   -5
c    3
dtype: int64

In [23]:
obj2.index

Index(['d', 'a', 'b', 'c'], dtype='object')

In [25]:
obj2['d']

4

In [26]:
import numpy as np

In [27]:
np.exp(obj2)

d      54.598150
a    1096.633158
b       0.006738
c      20.085537
dtype: float64

In [29]:
my_arr = np.arange(1000000)

In [30]:
my_list = list(range(1000000))


In [31]:
%time for _ in range(10): my_arr2 = my_arr * 2

CPU times: user 15.1 ms, sys: 13 ms, total: 28.1 ms
Wall time: 26.7 ms


In [32]:
%time for _ in range(10): my_list2 = [x * 2 for x in my_list]

CPU times: user 276 ms, sys: 55.5 ms, total: 332 ms
Wall time: 330 ms


In [33]:
data = np.random.randn(2, 3)

In [34]:
data

array([[-0.74539203,  0.79841257, -0.80655263],
       [ 0.3001733 , -0.40222979,  0.14064614]])

In [35]:
data * 10

array([[-7.45392029,  7.98412572, -8.06552626],
       [ 3.00173303, -4.02229792,  1.40646138]])

In [36]:
data + data

array([[-1.49078406,  1.59682514, -1.61310525],
       [ 0.60034661, -0.80445958,  0.28129228]])

## Creating ndarrays

In [37]:
data1 = [4, 5, 8.8, 9.89]

In [38]:
arr1 = np.array(data1)

In [39]:
arr1

array([4.  , 5.  , 8.8 , 9.89])

In [40]:
data2 = [[1, 2,3,4],[5,6,7,8]]

In [41]:
arr2 = np.array(data2)


In [42]:
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [43]:
arr2.ndim

2

In [44]:
arr2.shape

(2, 4)